name: Notice yarn.lock changes
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            main:
              - 'yarn.lock'
            docs:
              - 'docs/yarn.lock'
            example:
              - 'example/yarn.lock'
      - name: Notice yarn.lock changes
        if: steps.changed.outputs.main == 'true'
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'yarn.lock'
      - name: Notice docs/yarn.lock changes
        if: steps.changed.outputs.docs == 'true'
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'docs/yarn.lock'
      - name: Notice example/yarn.lock changes
        if: steps.changed.outputs.example == 'true'
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'example/yarn.lock'
