name: Validate iOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'ios/**'
  pull_request:
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'ios/**'

jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint Swift Files
        run: swiftlint ios --quiet | reviewdog -efm="%f:%l:%c:\ %t%*[^:]:\\ %m"

  SwiftFormat:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./ios
    steps:
      - uses: actions/checkout@v2

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
