name: Validate C++

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-cpp.yml'
      - 'package/cpp/**'
      - 'package/android/src/main/cpp/**'
      - 'package/ios/**'
  pull_request:
    paths:
      - '.github/workflows/validate-cpp.yml'
      - 'package/cpp/**'
      - 'package/android/src/main/cpp/**'
      - 'package/ios/**'

jobs:
  lint:
    name: Check clang-format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    strategy:
      matrix:
        path:
          - 'cpp'
          - 'android/src/main/cpp'
          - 'ios'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
          check-path: ${{ matrix.path }}

