name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'

jobs:
  lint:
    name: Gradle Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup node_modules
        run: yarn --cwd ..
      - name: Run Gradle Lint
        run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: android/build/reports/lint-results.xml
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install ktlint
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report-in-checkstyle-format.xml
      - uses: yutailang0119/action-ktlint@v1.0.0
        with:
          xml_path: build/ktlint-report-in-checkstyle-format.xml
